services:
    sonata.admin.article:
        class: Application\MainBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Article" }
        arguments:
            - ~
            - Application\MainBundle\Entity\Article
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationMainBundle]]