application_index:
    path:     /
    defaults: { _controller: ApplicationMainBundle:Default:index }


login:
    path:     /login
    defaults: { _controller: ApplicationMainBundle:Security:login }
login_check:
    path: /login_check

logout:
    path: /logout

account_register:
    path:     /register
    defaults: { _controller: ApplicationMainBundle:Security:register }

account_create:
    path:     /register/create
    defaults: { _controller: ApplicationMainBundle:Security:create }


admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin