Application\MainBundle\Entity\Article:
    type: entity
    table: article
    indexes:
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        isActive:
            type: boolean
            nullable: true
            comment: ''
            column: is_active
        text:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
