Application\MainBundle\Entity\Role:
    type: entity
    table: role
    uniqueConstraints:
        unique_role:
            columns:
                - role
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        role:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
    manyToMany:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: role
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
