Application\MainBundle\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        unique_username:
            columns:
                - username
        unique_email:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        isActive:
            type: boolean
            nullable: true
            comment: ''
            column: is_active
    manyToMany:
        role:
            targetEntity: Role
            cascade: {  }
            mappedBy: null
            inversedBy: user
            joinTable:
                name: user_to_role
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: role_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
